In [2]:
import numpy as np

## Basic Array Creation

In [2]:
# Creating a simple numpy arrays
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
# Creating a simple list in python
list1 = [1,2,3,4, "hi", 5.9]
list1

[1, 2, 3, 4, 'hi', 5.9]

In [4]:
# The numpy array converts all data into simple datatype
np.array(list1)


array(['1', '2', '3', '4', 'hi', '5.9'], dtype='<U32')

In [23]:
# Trying to create 3 dimensional lists is not possible
l = [ [1,2,3], [4,5,6], [7,8,9] ]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
# To convert the above list "l" into matrix, we can use array function
arr = np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Function

In [5]:
# Creating an array using range function
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# with steps
arr2 = np.arange(1,11,2)
arr2

array([1, 3, 5, 7, 9])

In [33]:
# Creating array of zeros
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
# Creating array of ones
arr = np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
# Creating arrays with linspace
arr4 = np.linspace(1,5,2)        
print(arr4)
# That means that we need 2 elements between 1 and 5 with even space or gap (Linear space).

arr5 = np.linspace(1,5,3)
print(arr5)

[1. 5.]
[1. 3. 5.]


# Random Number Generation

In [3]:
# five Random number generated between 0 to 1
np.random.rand(5) 


array([0.02069945, 0.6509658 , 0.57541603, 0.7422865 , 0.51524954])

In [4]:
#five Random number generated between -3 to 3
np.random.randn(10)

array([ 0.28750164,  1.06745822, -0.7712833 ,  1.14753292,  0.70594012,
       -0.51549031, -1.57173786,  1.5521939 , -1.19365872,  0.68614781])

In [8]:
# ten Random numbers generated between 10 and 20 
np.random.randint(10,20,10)

array([18, 13, 17, 18, 10, 14, 13, 16, 16, 13])

# Array Attributes

In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Dimensions of the array/matrix
arr.shape

(3, 3)

In [13]:
arr.size

9

In [14]:
arr.dtype

dtype('int32')

# Array Methods

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.min()

1

In [18]:
arr.max()

9

In [19]:
arr.sum()

45

In [22]:
# np sum asks for array and axis, axis = 0 means columns and axis = 1 means rows
np.sum(arr, axis=0)

array([12, 15, 18])

In [23]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [24]:
arr.mean()

5.0

In [25]:
arr.std()

2.581988897471611

In [34]:
# Index of the largest element
arr.argmax()

8

In [35]:
# Index of smallest element
arr.argmin()

0

# Reshaping and Resizing 

In [36]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [38]:
arr = arr.reshape(6,5)

In [39]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])