In [1]:
import numpy as np

## Basic Array Creation

In [2]:
# Creating a simple numpy arrays
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
# Creating a simple list in python
list1 = [1,2,3,4, "hi", 5.9]
list1

[1, 2, 3, 4, 'hi', 5.9]

In [4]:
# The numpy array converts all data into simple datatype
np.array(list1)


array(['1', '2', '3', '4', 'hi', '5.9'], dtype='<U32')

In [23]:
# Trying to create 3 dimensional lists is not possible
l = [ [1,2,3], [4,5,6], [7,8,9] ]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
# To convert the above list "l" into matrix, we can use array function
arr = np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Function

In [5]:
# Creating an array using range function
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# with steps
arr2 = np.arange(1,11,2)
arr2

array([1, 3, 5, 7, 9])

In [33]:
# Creating array of zeros
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
# Creating array of ones
arr = np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
# Creating arrays with linspace
arr4 = np.linspace(1,5,2)        
print(arr4)
# That means that we need 2 elements between 1 and 5 with even space or gap (Linear space).

arr5 = np.linspace(1,5,3)
print(arr5)

[1. 5.]
[1. 3. 5.]


# Random Number Generation

In [3]:
# five Random number generated between 0 to 1
np.random.rand(5) 


array([0.02069945, 0.6509658 , 0.57541603, 0.7422865 , 0.51524954])

In [4]:
#five Random number generated between -3 to 3
np.random.randn(10)

array([ 0.28750164,  1.06745822, -0.7712833 ,  1.14753292,  0.70594012,
       -0.51549031, -1.57173786,  1.5521939 , -1.19365872,  0.68614781])

In [8]:
# ten Random numbers generated between 10 and 20 
np.random.randint(10,20,10)

array([18, 13, 17, 18, 10, 14, 13, 16, 16, 13])

# Array Attributes

In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# Dimensions of the array/matrix
arr.shape

(3, 3)

In [13]:
arr.size

9

In [14]:
arr.dtype

dtype('int32')

# Array Methods

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr.min()

1

In [18]:
arr.max()

9

In [19]:
arr.sum()

45

In [22]:
# np sum asks for array and axis, axis = 0 means columns and axis = 1 means rows
np.sum(arr, axis=0)

array([12, 15, 18])

In [23]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [24]:
arr.mean()

5.0

In [25]:
arr.std()

2.581988897471611

In [34]:
# Index of the largest element
arr.argmax()

8

In [35]:
# Index of smallest element
arr.argmin()

0

# Reshaping and Resizing 

In [36]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [38]:
arr = arr.reshape(6,5)

In [39]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Array Indexing 

NUMPY INDEXING AND SLICING OF VECTORS 

In [11]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
# Indexing the array 
arr[6]

17

In [13]:
# Array Slicing
arr[5:9]

array([16, 17, 18, 19])

In [14]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
arr[3::2]

array([14, 16, 18, 20])

# Numpy Indexing and Slicing of Matrix

In [3]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[4] # The fourth row is sliced 

array([21, 22, 23, 24, 25])

In [13]:
arr[4,2] #The element on 4th row and 2nd column that is 23 is selected

23

In [15]:
# To slice out a matrix from a bigger one we can use this format
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [19]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [20]:
# To select a single column
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

# Boolean indexing 

In [21]:
arr =  np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
bool_indexing = arr % 2 == 0
bool_indexing

array([ True,  True,  True,  True,  True])

In [28]:
arr = arr[bool_indexing]
arr

array([12, 14, 16, 18, 20])

# Array Operations

#### ARITHEMETIC OPERATIONS

In [32]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(a1)
print(a2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [34]:
# Size of the arrays must be the same 
a3 = a1+a2
a3

array([ 7,  9, 11, 13, 15])

#### Broadcasting 

In [43]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [44]:
# Suppose we have to add 5 to each element 
arr + 5
# This is called broadcasting

array([15, 25, 35, 45])

#### Deep and shallow copy

In [ ]:
# Shallow copy

In [45]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
slice = a[2:6]
slice = slice * 10
slice

array([30, 40, 50, 60])

In [48]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# Deep copy
# Here we can see that changes done to b also changes the matrix a

In [58]:
b = a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
b [0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#  To do the above via shallow copy we can do this by 
# b = a.copy()

### Matrix Operations

In [64]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])


In [65]:
A

array([[1, 2],
       [3, 4]])

In [66]:
B

array([[5, 6],
       [7, 8]])

In [68]:
# This is invalid in matrix multiplication
A*B

array([[ 5, 12],
       [21, 32]])

In [70]:
# This gives accurate matrix multiplication
A @ B

array([[19, 22],
       [43, 50]])

In [71]:
#  Transpose  = Rows become columns and columns becomes row
A.T

array([[1, 3],
       [2, 4]])

In [72]:
B.T

array([[5, 7],
       [6, 8]])

In [74]:
(A @ B).T

array([[19, 43],
       [22, 50]])

### Advance array manipulation

In [77]:
#  Stacking array

In [79]:
# We cannot stack matrices, but we can stack vectors

In [81]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [82]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [83]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [78]:
# Splitting array 

In [85]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [87]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [88]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]